# Generated by Django 4.2 on 2023-05-01 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egresos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gastofijo',
            name='cuotas_restantes',
            field=models.IntegerField(default=0),
        ),
    ]
