# Generated by Django 4.2 on 2023-05-01 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngresoFijo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.CharField(max_length=255)),
                ('periodicidad', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='configuracion.periodicidad')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='configuracion.tipoingreso')),
            ],
        ),
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('detalle', models.CharField(max_length=255)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=11)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='configuracion.tipoingreso')),
            ],
        ),
    ]
