# Generated by Django 4.2 on 2023-05-01 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingresos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingresofijo',
            name='monto',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=11),
            preserve_default=False,
        ),
    ]
