# Generated by Django 4.2 on 2023-05-01 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingresos', '0002_ingresofijo_monto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingreso',
            name='fecha',
            field=models.DateField(auto_now=True),
        ),
    ]
