# Generated by Django 4.2 on 2023-05-01 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CajaCentral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingresos', models.DecimalField(blank=True, decimal_places=0, max_digits=11, null=True)),
                ('gastos', models.DecimalField(blank=True, decimal_places=0, max_digits=11, null=True)),
                ('saldo_en_caja', models.DecimalField(blank=True, decimal_places=0, max_digits=11, null=True)),
            ],
        ),
    ]
