# Generated by Django 4.2 on 2023-05-01 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cajacentral',
            name='nombre',
            field=models.CharField(blank=True, default='Ver detealle', max_length=50, null=True),
        ),
    ]
